name: Conventional Title Lint
on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  lint-pull-request-title:
    runs-on: ubuntu-24.04
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          version: "latest"

      - name: Lint pull request title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: uvx --from commitizen cz check -m "$PR_TITLE"
